services:
  igpt:
    image: "igpt"
    container_name: "igpt"
    restart: "unless-stopped"
    ports:
      - "7862:7862"
    volumes:
      - /data/InternGPT/model_zoo:/InternGPT/model_zoo
      - /data/InternGPT/certificate:/InternGPT/certificate
    entrypoint: "python"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      - "-u"
      - "app.py"
      - "--load"
      - "ImageOCRRecognition_cuda:0,Text2Image_cuda:0,SegmentAnything_cuda:0,ActionRecognition_cuda:0,VideoCaption_cuda:0,DenseCaption_cuda:0,ReplaceMaskedAnything_cuda:0,LDMInpainting_cuda:0,SegText2Image_cuda:0,ScribbleText2Image_cuda:0,Image2Scribble_cuda:0,Image2Canny_cuda:0,CannyText2Image_cuda:0,StyleGAN_cuda:0,Anything2Image_cuda:0,HuskyVQA_cuda:0"
      - "--https"
