services:
  igpt:
    image: "igpt"
    container_name: "igpt"
    restart: "unless-stopped"
    ports:
      - "7862:7862"
    volumes:
      - /data/InternGPT/model_zoo:/InternGPT/model_zoo
      - /data/InternGPT/certificate:/InternGPT/certificate
      - /data/InternGPT/checkpoints:/InternGPT/.checkpoints
      - /data/InternGPT/.EasyOCR:/root/.EasyOCR/model
    entrypoint: "python"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      - "-u"
      - "app.py"
      - "--load"
      - "HuskyVQA_cuda:0,SegmentAnything_cuda:0,ImageOCRRecognition_cuda:0,Anything2Image_cuda:0,ReplaceMaskedAnything_cuda:0"
      - "--https"
